# Generated by Django 3.1.5 on 2021-01-28 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('value', models.TextField()),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.TextField()),
                ('provider', models.TextField(null=True)),
                ('start_time', models.DateField(null=True)),
                ('end_time', models.DateField(null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.TextField()),
                ('company', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('start_time', models.DateField(null=True)),
                ('end_time', models.DateField(null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_Summaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('summary', models.TextField()),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('story', models.TextField()),
                ('keywords', models.TextField()),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume_Education_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.educations')),
            ],
        ),
        migrations.CreateModel(
            name='Resume_Work_History_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_profile_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.job_profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('score', models.IntegerField()),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resumes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.TextField()),
                ('profile_summary_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_api.profile_summaries')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume_Work_History_Project_Summary_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_summary_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.profile_summaries')),
                ('resume_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resumes')),
                ('resume_wh_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resume_work_history_map')),
            ],
        ),
        migrations.AddField(
            model_name='resume_work_history_map',
            name='resume_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resumes'),
        ),
        migrations.CreateModel(
            name='Resume_Skill_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resumes')),
                ('skill_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.skills')),
            ],
        ),
        migrations.CreateModel(
            name='Resume_Project_Summary_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_summary_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.profile_summaries')),
                ('resume_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resumes')),
            ],
        ),
        migrations.CreateModel(
            name='Resume_Education_Project_Summary_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_summary_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.profile_summaries')),
                ('resume_edu_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resume_education_map')),
                ('resume_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resumes')),
            ],
        ),
        migrations.AddField(
            model_name='resume_education_map',
            name='resume_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resumes'),
        ),
        migrations.CreateModel(
            name='Resume_Content_Section_Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.TextField()),
                ('position', models.IntegerField()),
                ('resume_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resumes')),
            ],
        ),
        migrations.CreateModel(
            name='Resume_Contact_Detail_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_details_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.contact_details')),
                ('resume_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resumes')),
            ],
        ),
        migrations.CreateModel(
            name='Projects_Summaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('project_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.projects')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
