# Generated by Django 3.1.5 on 2021-01-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumes',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
