# Generated by Django 3.1.5 on 2021-01-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_resumes_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume_contact_detail_map',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume_education_map',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume_education_project_summary_map',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume_skill_map',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume_work_history_map',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume_work_history_project_summary_map',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resume_content_section_positions',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resumes',
            name='title',
            field=models.TextField(),
        ),
    ]
