# Generated by Django 3.1.5 on 2021-01-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_auto_20210129_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_content_section_positions',
            name='position',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='resume_education_map',
            name='position',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='resume_skill_map',
            name='position',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='resume_work_history_map',
            name='position',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='resume_work_history_project_summary_map',
            name='position',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
