# Generated by Django 3.1.5 on 2021-02-01 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_auto_20210201_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_project_summary_map',
            name='project_summary_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.projects_summaries'),
        ),
    ]
