# Generated by Django 3.1.5 on 2021-02-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0007_resume_content_section_positions_user_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume_content_section_positions',
            name='resume_fk',
        ),
        migrations.RemoveField(
            model_name='resume_content_section_positions',
            name='user_fk',
        ),
        migrations.RemoveField(
            model_name='resume_education_map',
            name='education_fk',
        ),
        migrations.RemoveField(
            model_name='resume_education_map',
            name='resume_fk',
        ),
        migrations.RemoveField(
            model_name='resume_education_project_summary_map',
            name='project_summary_fk',
        ),
        migrations.RemoveField(
            model_name='resume_education_project_summary_map',
            name='resume_edu_fk',
        ),
        migrations.RemoveField(
            model_name='resume_education_project_summary_map',
            name='resume_fk',
        ),
        migrations.RemoveField(
            model_name='resume_project_summary_map',
            name='project_summary_fk',
        ),
        migrations.RemoveField(
            model_name='resume_project_summary_map',
            name='resume_fk',
        ),
        migrations.RemoveField(
            model_name='resume_skill_map',
            name='resume_fk',
        ),
        migrations.RemoveField(
            model_name='resume_skill_map',
            name='skill_fk',
        ),
        migrations.RemoveField(
            model_name='resume_work_history_map',
            name='job_profile_fk',
        ),
        migrations.RemoveField(
            model_name='resume_work_history_map',
            name='resume_fk',
        ),
        migrations.RemoveField(
            model_name='resume_work_history_project_summary_map',
            name='project_summary_fk',
        ),
        migrations.RemoveField(
            model_name='resume_work_history_project_summary_map',
            name='resume_fk',
        ),
        migrations.RemoveField(
            model_name='resume_work_history_project_summary_map',
            name='resume_wh_fk',
        ),
        migrations.RemoveField(
            model_name='resumes',
            name='profile_summary_fk',
        ),
        migrations.RemoveField(
            model_name='resumes',
            name='user_fk',
        ),
        migrations.DeleteModel(
            name='Resume_Contact_Detail_Map',
        ),
        migrations.DeleteModel(
            name='Resume_Content_Section_Positions',
        ),
        migrations.DeleteModel(
            name='Resume_Education_Map',
        ),
        migrations.DeleteModel(
            name='Resume_Education_Project_Summary_Map',
        ),
        migrations.DeleteModel(
            name='Resume_Project_Summary_Map',
        ),
        migrations.DeleteModel(
            name='Resume_Skill_Map',
        ),
        migrations.DeleteModel(
            name='Resume_Work_History_Map',
        ),
        migrations.DeleteModel(
            name='Resume_Work_History_Project_Summary_Map',
        ),
        migrations.DeleteModel(
            name='Resumes',
        ),
    ]
