# Generated by Django 3.1.5 on 2021-02-12 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_api', '0008_auto_20210212_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('job_profile_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_api.job_profiles')),
                ('profile_summary_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_api.profile_summaries')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume_Subsections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('position', models.IntegerField()),
                ('resume_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resumes')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('resume_fk', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Skill_Resume_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('resume_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resumes')),
                ('resume_subsection_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resume_subsections')),
                ('skill_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.skills')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('resume_subsection_fk', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Project_Summary_Resume_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('project_summary_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.projects_summaries')),
                ('resume_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resumes')),
                ('resume_subsection_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resume_subsections')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('resume_subsection_fk', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Project_Resume_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('project_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.projects')),
                ('resume_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resumes')),
                ('resume_subsection_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resume_subsections')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('resume_subsection_fk', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Education_Resume_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('education_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.educations')),
                ('resume_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resumes')),
                ('resume_subsection_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resume_subsections')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('resume_subsection_fk', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Contact_Resume_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('contact_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.contact_details')),
                ('resume_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resumes')),
                ('resume_subsection_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resume_subsections')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('resume_subsection_fk', 'position')},
            },
        ),
    ]
