# Generated by Django 3.1.5 on 2021-02-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0010_auto_20210213_0401'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact_resume_map',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='education_resume_map',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='project_resume_map',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='project_summary_resume_map',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='resume_subsections',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='skill_resume_map',
            unique_together=set(),
        ),
    ]
