# Generated by Django 3.1.5 on 2021-02-18 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_api', '0011_auto_20210213_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiece_Resume_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('template_prop', models.TextField(null=True)),
                ('job_profile_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.job_profiles')),
                ('resume_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resumes')),
                ('resume_subsection_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.resume_subsections')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
